#!/usr/bin/env python3
import sys
from pathlib import Path

__version__ = "0.1.0"

import signatures

CHUNK_SIZE = 512
DEEP_SCAN = False
RECURSIVE = False

from analyzers import Result

def analyze(filepath):
    print(f"\n{filepath}: ", end="")
    
    with open(filepath, "rb") as file:
        data = file.read(CHUNK_SIZE)

    if not DEEP_SCAN:
        candidates = signatures.identify(data)
        if not candidates:
            if signatures.checkutf8(data):
                print(" Text Data")
            else:
                print(" Unknown file type.")
        else:
            for candidate in candidates:
                analyzer = candidate.get("analyzer")
                if analyzer:
                    result = analyzer(filepath)
                    printResult(result)
                else:
                    result = Result(filepath, candidate["name"])
                    result.validHeader(candidate["name"])
                    result.addEvidence(0, "! No specialized analyzer implemented")
                    result.integrity = None;
                    printResult(result)
    else:
        candidates = signatures.deepIdentify(filepath)
        if not candidates:
            if signatures.checkutf8(data):
                    print(" Text Data")
            else:
                print(" Unknown file type.")
        else:
            for candidate in candidates:
                match = candidate.get("filetype")
                analyzer = match.get("analyzer")
                if analyzer:
                    result = analyzer(filepath, candidate["offset"])
                    if result and result.confidence >= 50:
                        printResult(result)
                else:
                    print(" ! potentially", match['name'], "at offset", candidate['offset'])

def printResult(result):
    CYAN = "\033[36m"
    WHITE = "\033[97m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    RED = "\033[31m"
    RESET = "\033[0m"
    BOLD = "\033[1m"

    integrity = result.integrity
    confidence = result.confidence

    if integrity is None:
        integrity = "Not analyzed"
        status = ""
        color = WHITE
    elif integrity >= 80:
        color = GREEN
        status = ""
    elif integrity >= 50:
        color = YELLOW
        status =  "Probably corrupted "
    else:
        color = RED
        status = "Corrupted "

    if confidence >= 75:
        conf = GREEN
    elif confidence >= 50:
        conf = YELLOW
    else:
        conf = RED

    print(f"\n{color}  {status}{result.type}{RESET} {f"at offset {result.offset}" if DEEP_SCAN else ""}")

    print("  Reasoning:")
    for reason in result.reasons:
        print(f"\t{reason}")

    print("  Confidence:", conf, confidence, RESET)
    print("  Integrity:", color, integrity, RESET)
    warnings = result.warnings
    if(warnings):
        print("  Warnings:")
        for warning in warnings:
            print(YELLOW, f"\t{warning}", RESET)

def printHelp():
    print(f"""
    wtf {__version__}

    Usage:
        wtf [options] <file> [file...]
        wtf [options] <directory>

    Options:
        --deep            Scan entire file for embedded signatures
        -r, --recursive   Recurse into directories
        -v, --version     Show version information
        -h, --help        Show this help page
    """
    )

def scanPath(path):
    p = Path(path)

    if p.is_file():
        analyze(p)

    elif p.is_dir():
        if RECURSIVE:
            for file in p.rglob("*"):
                if file.is_file():
                    analyze(file)
        else:
            for file in p.iterdir():
                if file.is_file():
                    analyze(file)

    else:
        print(f"{path}: not a valid file")

if __name__ == "__main__":
    args = sys.argv[1:]

    if not args:
        print("Try 'wtf --help' for more information.")
        sys.exit(1)

    if "--help" in args or "-h" in args:
        printHelp()
        sys.exit(0)

    if "--version" in args or "-v" in args:
        print(f"wtf {__version__}")
        sys.exit(0)

    if "--deep" in args:
        DEEP_SCAN = True
        args.remove("--deep")

    if "-r" in args:
        RECURSIVE = True
        args.remove("-r")

    if "--recursive" in args:
        RECURSIVE = True
        args.remove("--recursive")

    if not args:
        print("No input files specified")
        sys.exit(1)

    for path in args:
        scanPath(path)