#!/usr/bin/env python3
import sys
from pathlib import Path

import signatures

CHUNK_SIZE = 500
DEEP_SCAN = False

# this is only temporary while i write specialized analyzers for each file type.
# im not writing 30 analyzers in one go ;-;
from analyzers import Result

def analyze(filepath):
    with open(filepath, "rb") as file:
        data = file.read(512)

    if not DEEP_SCAN:
        candidates = signatures.identify(data)
        if not candidates:
            if signatures.checkutf8(data):
                print(f"\n{filepath}")
                print(" Text Data")
            else:
                print(f"\n{filepath}")
                print(" Unknown file type.")
        else:
            for candidate in candidates:
                analyzer = candidate.get("analyzer")
                if analyzer:
                    result = analyzer(filepath)
                    if result:
                        printResult(result)
                        continue
                
                result = Result(file, candidate["name"])
                result.validHeader(candidate["name"])
                printResult(result)
    else:
        candidates = signatures.deepIdentify(filepath)
        print(filepath)
        if not candidates:
            if signatures.checkutf8(data):
                    print(" Text Data")
            else:
                print(" Unknown file type.")
        else:
            for candidate in candidates:
                match = candidate.get("filetype")
                analyzer = match.get("analyzer")
                if analyzer:
                    result = analyzer(filepath, candidate["offset"])
                    if result:
                        printResult(result)
                else:
                    print(" ! potentially", match['name'], "at offset", candidate['offset'])

def printResult(result):
    CYAN = "\033[36m"
    WHITE = "\033[97m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    RED = "\033[31m"
    RESET = "\033[0m"
    BOLD = "\033[1m"

    integrity = result.integrity

    if integrity >= 80:
        color = GREEN
        status = ""
    elif integrity >= 50:
        color = YELLOW
        status =  "Probably corrupted "
    else:
        color = RED
        status = "Corrupted "

    print(f"\n{result.file}")
    print(f"{color}  {status}{result.type}{RESET} {f"at offset {result.offset}" if DEEP_SCAN else ""}")

    print("  Reasoning:")
    for reason in result.reasons:
        print(f"\t{reason}")

    print("  Integrity:", color, integrity, RESET)
    warnings = result.warnings
    if(warnings):
        print("  Warnings:", YELLOW)
        for warning in warnings:
            print(f"\t{warning}")
        print(RESET)

if __name__ == "__main__":

    if len(sys.argv) < 2:
        print("Usage: wtf <file> [file...]")
        sys.exit(1)
    
    paths = sys.argv[1:]
    if sys.argv[1] == "--deep":
        DEEP_SCAN = True
        paths = sys.argv[2:]
    
    for filepath in paths:
        p = Path(filepath)
        if p.is_dir():
            for file in p.rglob("*"):
                if file.is_file():
                    analyze(file)

        elif p.is_file():   
           analyze(filepath)
                    
        else:
            print(f"{filepath}: not a valid file")
