#!/usr/bin/env python3
import sys
import os

import signatures

def checkutf8(data) -> bool:
    try:
        data.decode("utf-8")
    except UnicodeDecodeError as e:
        # handle multi byte UTF 8 characters if found at edge
        if e.reason == "unexpected end of data": return True 
        else: return False
    
    return True

def analyze(filepath):
    print(f"\n{filepath}")

    with open(filepath, "rb") as file:
        data = file.read(512)

    candidates = signatures.identify(data)
    if not candidates:
        if checkutf8(data):
            print(" Text Data")
        else:
            print(" Unknown file type.")
    else:
        for candidate in candidates:
            probe = candidate.get("probe")
            if probe:
                result = probe(filepath)
                if result:
                    print(f" {result["name"]}")
                    continue
            
            print(f" {candidate["name"]}")


if __name__ == "__main__":

    if len(sys.argv) < 2:
        print("Usage: wtf <file> [file...]")
        sys.exit(1)
    
    paths = sys.argv[1:]
    for filepath in paths:
        
        if os.path.isdir(filepath):
            for root, dirs, files in os.walk(filepath):
                for file in files:
                    analyze(os.path.join(root, file))

        elif os.path.isfile(filepath):    
           analyze(filepath)
                    
        else:
            print(f"{filepath}: not a valid file")
            continue
